<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>
    <RootNamespace>QuickLook.Next.App</RootNamespace>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <UseWinUI>true</UseWinUI>
    <WindowsPackageType>None</WindowsPackageType>
    <WindowsAppSDKSelfContained>true</WindowsAppSDKSelfContained>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <DefineConstants>$(DefineConstants);DISABLE_XAML_GENERATED_MAIN</DefineConstants>
    <ApplicationIcon>Assets\QuickLookNext.ico</ApplicationIcon>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ProjectPriIndexName Condition="'$(ProjectPriIndexName)' == ''">SherlockChiang.QuickLookNext</ProjectPriIndexName>
    <ProjectPriFileName>resources.pri</ProjectPriFileName>
    <QuickLookUsesNative>true</QuickLookUsesNative>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.WindowsAppSDK" Version="2.3.1" />
    <PackageReference Include="Microsoft.Windows.SDK.BuildTools" Version="10.0.28000.2526" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\QuickLook.Next.Core\QuickLook.Next.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="Assets\**\*"
             CopyToOutputDirectory="PreserveNewest"
             CopyToPublishDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
